meta:
  author: nikservik
  version: rev1.3
units:
  column_stagger: 20.97
  column_connection_width: 2
  sw: 18
  sh: 16
  mcu_width: 23.5
  mcu_height: 21.6
  mcu_x_offset: 1
  xiao_width: 18.5
  xiao_height: 21
  xiao_x_offset: 1
  thumbs_x_offset: 62
  thumbs_y_offset: 49
points:
  zones:
    matrix:
      key.padding: column_stagger
      anchor:
        rotate: 10
        shift: [100, -100]
      mirror:
        ref: matrix_inner_home
        distance: u
      columns:
        pinky:
          key:
            column_net: C1
            mirror.column_net: C10
        ring:
          key:
            splay: -5
            stagger: 11.395
            spread: 21.556
            column_net: C2
            mirror.column_net: C9
        middle:
          key:
            splay: -5
            stagger: 3.297
            spread: 21.411
            column_net: C3
            mirror.column_net: C8
        index:
          key:
            stagger: -4
            spread: u
            column_net: C4
            mirror.column_net: C7
        inner:
          key:
            stagger: -7
            spread: u
            column_net: C5
            mirror.column_net: C6
      rows:
        home:
          row_net: R2
          mirror.row_net: R2
        top:
          row_net: R1
          mirror.row_net: R1
        bottom:
          row_net: R3
          mirror.row_net: R3
          adjust.shift: [0, -3column_stagger]
    thumbs:
      mirror:
        ref: thumbs_near_only
        distance: -2 thumbs_x_offset + u
      anchor:
        ref: matrix_inner_home
        shift: [thumbs_x_offset, thumbs_y_offset]
      columns:
        near:
          key:
            column_net: C3
            mirror.column_net: C8
        home:
          key:
            spread: 21.11
            stagger: -3.52
            splay: -18.952
            column_net: C4
            mirror.column_net: C7
        far:
          key:
            spread: 21.11
            stagger: -3.52
            splay: -18.952
            column_net: C5
            mirror.column_net: C6
      rows:
        only:
          row_net: R4
outlines:
  left_matrix:
    keys:
      what: rectangle
      where: 
        - /^matrix_.*/
      size: [sw, sh]
      corner: 1
    column_connections:
      what: rectangle
      where:
        - /^matrix_.*_home/
      size: [column_connection_width, 2column_stagger]      
    pinky_to_ring:
      what: rectangle
      where:
        ref: matrix_pinky_home
        shift: [sw/2, sh/2 - 1.5]
      size: [8, 3]
    ring_to_pinky:
      what: rectangle
      where:
        ref: matrix_ring_home
        shift: [-sw/2, -sh/2 + 1.5]
      size: [8, 3]
    ring_to_middle:
      what: rectangle
      where:
        ref: matrix_ring_home
        shift: [sw/2 - 0.5 , sh/2 - 0.5]
      size: [1, 1]
    middle_to_ring:
      what: rectangle
      where:
        ref: matrix_middle_home
        shift: [-sw/2, -sh/2 + 5.802]
      size: [7.546, 11.604]
    middle_to_index:
      what: rectangle
      where:
        ref: matrix_middle_home
        shift: [sw/2, -sh/2 + 6]
      size: [4, 12]
    index_to_inner:
      what: rectangle
      where:
        ref: matrix_index_home
        shift: [sw/2, -sh/2 + 4.5]
      size: [4, 9]
  right_matrix:
    keys:
      what: rectangle
      where: 
        - /mirror_matrix_.*/
      size: [sw, sh]
      corner: 1
    column_connections:
      what: rectangle
      where:
        - /mirror_matrix_.*_home/
      size: [column_connection_width, 2column_stagger]      
    mirror_pinky_to_ring:
      what: rectangle
      where:
        ref: mirror_matrix_pinky_home
        shift: [sw/2, sh/2 - 1.5]
      size: [8, 3]
    mirror_ring_to_pinky:
      what: rectangle
      where:
        ref: mirror_matrix_ring_home
        shift: [-sw/2, -sh/2 + 1.5]
      size: [8, 3]
    mirror_ring_to_middle:
      what: rectangle
      where:
        ref: mirror_matrix_ring_home
        shift: [sw/2 - 0.5 , sh/2 - 0.5]
      size: [1, 1]
    mirror_middle_to_ring:
      what: rectangle
      where:
        ref: mirror_matrix_middle_home
        shift: [-sw/2, -sh/2 + 5.802]
      size: [7.546, 11.604]
    mirror_middle_to_index:
      what: rectangle
      where:
        ref: mirror_matrix_middle_home
        shift: [sw/2, -sh/2 + 6]
      size: [4, 12]
    mirror_index_to_inner:
      what: rectangle
      where:
        ref: mirror_matrix_index_home
        shift: [sw/2, -sh/2 + 4.5]
      size: [4, 9]
  _left_thumbs:
    thumb_keys:
      what: rectangle
      where: 
        - /^thumbs_.*/
      size: [sw, sh]
    mcu:
      what: rectangle
      where: 
        ref: thumbs_near_only
        shift: [-(xiao_width + sw)/2 - xiao_x_offset - mcu_x_offset, (mcu_height - sh)/2]
      size: [xiao_width + 2xiao_x_offset, mcu_height]
    mcu_switches:
      what: rectangle
      where: 
        ref: thumbs_near_only
        shift: [-(mcu_width + sw)/2 - mcu_x_offset, -0.5sh + 3]
      size: [mcu_width, 6]
    thumb_to_mcu:
      what: rectangle
      where:
        ref: thumbs_near_only
        shift: [-(sw + mcu_x_offset)/2, 0]
      size: [mcu_x_offset + 2, sh]
    near_to_home:
      what: polygon
      points:
        - ref: thumbs_near_only
          shift: [0.5sw, 0.5sh]
        - ref: thumbs_near_only
          shift: [0.5sw, -0.5sh]
        - ref: thumbs_home_only
          shift: [-0.5sw, -0.5sh]
        - ref: thumbs_home_only
          shift: [-0.5sw, 0.5sh]
    home_to_far:
      what: polygon
      points:
        - ref: thumbs_home_only
          shift: [0.5sw, 0.5sh]
        - ref: thumbs_home_only
          shift: [0.5sw, -0.5sh]
        - ref: thumbs_far_only
          shift: [-0.5sw, -0.5sh]
        - ref: thumbs_far_only
          shift: [-0.5sw, 0.5sh]
  _right_thumbs:
    thumb_keys:
      what: rectangle
      where: 
        - /mirror_thumbs_.*/
      size: [sw, sh]
    mirror_mcu:
      what: rectangle
      where: 
        ref: mirror_thumbs_near_only
        shift: [-(xiao_width + sw)/2 - xiao_x_offset - mcu_x_offset, (mcu_height - sh)/2]
      size: [xiao_width + 2xiao_x_offset, mcu_height]
    mirror_mcu_switches:
      what: rectangle
      where: 
        ref: mirror_thumbs_near_only
        shift: [-(mcu_width + sw)/2 - mcu_x_offset, -0.5sh + 3]
      size: [mcu_width, 6]
    mirror_thumb_to_mcu:
      what: rectangle
      where:
        ref: mirror_thumbs_near_only
        shift: [-(sw + mcu_x_offset)/2, 0]
      size: [mcu_x_offset + 2, sh]
    mirror_near_to_home:
      what: polygon
      points:
        - ref: mirror_thumbs_near_only
          shift: [0.5sw, 0.5sh]
        - ref: mirror_thumbs_near_only
          shift: [0.5sw, -0.5sh]
        - ref: mirror_thumbs_home_only
          shift: [-0.5sw, -0.5sh]
        - ref: mirror_thumbs_home_only
          shift: [-0.5sw, 0.5sh]
    mirror_home_to_far:
      what: polygon
      points:
        - ref: mirror_thumbs_home_only
          shift: [0.5sw, 0.5sh]
        - ref: mirror_thumbs_home_only
          shift: [0.5sw, -0.5sh]
        - ref: mirror_thumbs_far_only
          shift: [-0.5sw, -0.5sh]
        - ref: mirror_thumbs_far_only
          shift: [-0.5sw, 0.5sh]
  left_thumbs:
    - name: _left_thumbs
      fillet: 1 
  right_thumbs:
    - name: _right_thumbs
      fillet: 1 
pcbs:
  left:
    outlines.main.outline: left_matrix
    footprints:
      keys:
        what: gateron-lowprofile
        where: 
          - /^matrix_.*/
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          hotswap: true
          diode: true
          diode_shift: [7.5, 0]
          diode_via: false
      left_socket:
        what: fpc-socket
        where:
          ref: matrix_index_home
          shift: [0, -6.9]
          rotate: 180
        params:
          side: 'B'
          P1: 'R3'
          P2: 'R2'
          P3: 'R1'
          P4: 'C5'
          P5: 'C4'
          P6: 'C3'
          P7: 'C2'
          P8: 'C1'
  right:
    outlines.main.outline: right_matrix
    footprints:
      keys:
        what: gateron-lowprofile
        where: 
          - /mirror_matrix_.*/
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          hotswap: true
          diode: true
          diode_shift: [7.5, 0]
          diode_via: false
      socket:
        what: fpc-socket
        where:
          ref: mirror_matrix_index_home
          shift: [0, -6.9]
          rotate: 180
        params:
          side: 'B'
          P1: 'C10'
          P2: 'C9'
          P3: 'C8'
          P4: 'C7'
          P5: 'C6'
          P6: 'R1'
          P7: 'R2'
          P8: 'R3'
  left_thumbs:
    outlines.main.outline: left_thumbs
    footprints:
      keys:
        what: gateron-lowprofile
        where: 
          - /^thumbs_.*/
        params:
          from: "{{column_net}}"
          to: "{{row_net}}_{{column_net}}"
          hotswap: true
          diode: false
          diode_shift: [7.5, 0]
          diode_via: false
      diode_set:
        what: diode-3set
        where:
          ref: thumbs_near_only
          shift: [0.5sw, -2]
          rotate: 270
        params:
          from1: 'R4_C3'
          from2: 'R4_C4'
          from3: 'R4_C5'
          to: 'R4'
      mcu:
        what: xiao-ble
        where:
          ref: thumbs_near_only
          shift: [-0.5(sw + xiao_width) - mcu_x_offset - xiao_x_offset, (xiao_height - sh)/2 + 0.5]
          rotate: 180
        params:
          side: 'F'
          holes: false
          P1: 'C1'
          P2: 'C2'
          P3: 'C3'
          P4: 'C4'
          P5: 'C5'
          P7: 'R1'
          P8: 'R2'
          P9: 'R3'
          P10: 'R4'
      socket:
        what: fpc-socket
        where:
          ref: thumbs_near_only
          shift: [-u, 10]
        params:
          side: 'B'
          P1: 'C1'
          P2: 'C2'
          P3: 'C3'
          P4: 'C4'
          P5: 'C5'
          P6: 'R1'
          P7: 'R2'
          P8: 'R3'
      power_switch:
        what: switch-power
        where:
          ref: thumbs_near_only
          shift: [-0.5sw + 1, -1]
          rotate: 90
        params:
          side: 'B'
          from: 'BATP'
          to: 'BAT_P'       
      reset_switch:
        what: button
        where:
          ref: thumbs_near_only
          shift: [-0.5(sw + xiao_width) - mcu_x_offset - xiao_x_offset - 3, 1]
          rotate: 0
        params:
          side: 'B'
          from: 'GND'
          to: 'RST'
      battery_connector:
        what: battery-pad
        where:
          ref: thumbs_near_only
          shift: [-0.5sw - xiao_width - 2xiao_x_offset - mcu_x_offset - 1.5, -5]
          rotate: 90
        params:
          pos: 'BAT_P'
          neg: 'GND'
      mounthole:
        what: mounting-hole
        where:
          ref: thumbs_home_only
          shift: [0.5sw + 1.8, 0]
        params:
          via: false
  right_thumbs:
    outlines.main.outline: right_thumbs
    footprints:
      keys:
        what: gateron-lowprofile
        where: 
          - /mirror_thumbs_.*/
        params:
          from: "{{column_net}}"
          to: "{{row_net}}_{{column_net}}"
          hotswap: true
          diode: false
          diode_shift: [7.5, 0]
          diode_via: false
      diode_set:
        what: diode-3set
        where:
          ref: mirror_thumbs_near_only
          shift: [0.5sw, -2]
          rotate: 270
        params:
          from1: 'R4_C6'
          from2: 'R4_C7'
          from3: 'R4_C8'
          to: 'R4'
      mcu:
        what: xiao-ble
        where:
          ref: mirror_thumbs_near_only
          shift: [-0.5(sw + xiao_width) - mcu_x_offset - xiao_x_offset, (xiao_height - sh)/2 + 0.5]
          rotate: 180
        params:
          side: 'F'
          holes: false
          P1: 'C10'
          P2: 'C9'
          P3: 'C8'
          P4: 'C7'
          P5: 'C6'
          P7: 'R1'
          P8: 'R2'
          P9: 'R3'
          P10: 'R4'
          BATP: 'BATP'
          GND: 'GND'
          RST: 'RST'
          P0: 'P0'
          P6: 'P6'
          RAW3V3: 'RAW3V3'
          RAW5V: 'RAW5V'
      socket:
        what: fpc-socket
        where:
          ref: mirror_thumbs_near_only
          shift: [-u, 10]
        params:
          side: 'B'
          P1: 'R3'
          P2: 'R2'
          P3: 'R1'
          P4: 'C6'
          P5: 'C7'
          P6: 'C8'
          P7: 'C9'
          P8: 'C10'
      power_switch:
        what: switch-power
        where:
          ref: mirror_thumbs_near_only
          shift: [-0.5sw + 1, -1]
          rotate: 270
        params:
          side: 'B'
          from: 'BAT_P'
          to: 'BATP'       
      reset_switch:
        what: button
        where:
          ref: mirror_thumbs_near_only
          shift: [-0.5(sw + xiao_width) - mcu_x_offset - xiao_x_offset + 3, 1]
          rotate: 0
        params:
          side: 'B'
          from: 'GND'
          to: 'RST'
      battery_connector:
        what: battery-pad
        where:
          ref: mirror_thumbs_near_only
          shift: [-0.5sw - xiao_width - 2xiao_x_offset - mcu_x_offset - 1.5, -5.4]
          rotate: 270
        params:
          pos: 'BAT_P'
          neg: 'GND'        
      mounthole:
        what: mounting-hole
        where:
          ref: mirror_thumbs_home_only
          shift: [0.5sw + 1.8, 0]
        params:
          via: false
